TEST_ALL_CARDS = [[
    [1, '&spades;'],
    [2, '&clubs;'],
    [3, '&spades;'],
    [3, '&clubs;'],
    [4, '&hearts;'],
    [5, '&clubs;'],
    [5, '&diams;'],
    [8, '&diams;'],
    [8, '&clubs;'],
    [9, '&hearts;'],
    [9, '&spades;'],
    [11, '&hearts;'],
    [12, '&spades;'],
    [13, '&diams;']
], [
    [1, '&clubs;'],
    [2, '&hearts;'],
    [2, '&spades;'],
    [4, '&diams;'],
    [4, '&spades;'],
    [7, '&spades;'],
    [7, '&diams;'],
    [7, '&clubs;'],
    [10, '&spades;'],
    [11, '&clubs;'],
    [11, '&diams;'],
    [12, '&hearts;'],
    [14, '&hearts;'],
], [
    [1, '&diams;'],
    [1, '&hearts;'],
    [2, '&diams;'],
    [3, '&diams;'],
    [4, '&clubs;'],
    [5, '&spades;'],
    [6, '&diams;'],
    [7, '&hearts;'],
    [8, '&hearts;'],
    [9, '&clubs;'],
    [12, '&clubs;'],
    [13, '&clubs;'],
    [13, '&spades;'],
    [13, '&hearts;'],
], [
    [3, '&hearts;', True],
    [5, '&hearts;', True],
    [6, '&hearts;', True],
    [6, '&spades;', True],
    [6, '&clubs;', True],
    [8, '&spades;', True],
    [9, '&diams;', True],
    [10, '&hearts;', True],
    [10, '&clubs;', True],
    [10, '&diams;', True],
    [11, '&spades;', True],
    [12, '&diams;', True],
    [14, '&spades;', True],
], ]
