player1:
  name: Richard
  type: Holder
  console: false
player2:
  name: Silvia
  type: Simple
  console: false
player3:
  name: Sara
  type: Splitter
  console: false
player4:
  name: snAkbar
  type: Naive
  console: true
screen:
  width: 900
  height: 600
