player1:
  name: snAkbar
  type: Splitter
  console: false
player2:
  name: Richard
  type_: Holder
  type: Splitter
  console: false
player3:
  name: Silvia
  type_: Simple
  type: Splitter
  console: false
player4:
  name: Sara
  type_: Naive
  type: Network
  model: splitter_rl_v2
  console: false
screen:
  width: 900
  height: 600
